version: '3'

services:
  tcc-postgres:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sonar
      POSTGRES_USER: sonar
  tcc-sonar:
    image: sonarqube
    ports:
    - "9000:9000"
    environment:
      sonar.jdbc.username: sonar
      sonar.jdbc.password: sonar
      sonar.jdbc.url: jdbc:postgresql://tcc-postgres:5432/sonar
    depends_on:
    - tcc-postgres